### ISSUE TITLE
Error when running profileNJ

### ISSUE THREAD

**Issue by YoannAnselmetti** [UdeM-LBIT/profileNJ#6]
Hi Emmanuel,

I get an error with your last version of profileNJ.
When I run it, I get the following error:
  File "bin/profileNJ", line 290
    print([" ".join([x)+"\n" for x in distance_matrix[:]])
                      ^
SyntaxError: invalid syntax

I solved it by replacing line 290:
   print([" ".join([x)+"\n" for x in distance_matrix[:]])
by:
   print(" ".join([x+"\n" for x in distance_matrix[:]])) 

Yoann Anselmetti

**Comment by maclandrol** [comment]
I have a `profileNJ.py` file in the root directory. My changes are often done on that file before merging with 
bin/profileNJ. I forget to merge this time.

Thanks. Commit  56cbdd2 should fix it.
